### ISSUE TITLE
Stor v4 release checklist

### ISSUE THREAD

**Issue by jtratner** [counsyl/stor#131]
- [ ] Upload renders well on test pypi
- [ ] Docs get built and pushed with each build (or we switch to read the docs) - we have new pipeline on backend
- [ ] confirm integration tests run with deploy
- [ ] build badge points to GH Actions

CC @pkaleta @anujkumar93 
(Module refactor of stor will be stor v5 now)
